---
title: "Abu_Muslim"
format: html
---

---
title: "Abu Muslim: The Forgotten Figurehead of the Abbasid Revolution"
author: "Henry Nadel"
date: "5/10/2024"
course: "Islam and the End of Time"
instructor: "Prof. Jamel Velji"
format: pdf
---

The Abbasid Caliphate is heralded by many as the golden age of Islam for its cultural advancements and longevity lasting over three centuries that were defined by stability. However, their rise to power was far less idealistic and has been shrouded in apocalyptic mysteries by the Abbasids to create a cleaner narrative. Due to the swift nature of how the Abbasids took over the caliphate, along with the narrative control they claimed after their victory, it's quite difficult to look past the historical descriptions written from within the Abbasid empire. However, piecing together the details from alternate sources, the story of a man named Abu Muslim begins to emerge. Abu Muslim played a critical role in the strategic mobilization of messianic aspirations that allowed the Abbasids to swiftly overtake the Ummayads, yet his story is seldom included. This paper aims to delineate Abu Muslim's pivotal role, and in doing so, address how the interjection of Abu Muslim's legacy alters our understanding of the eschatological dimensions inherent in the Abbasid Revolution. Through a nuanced analysis of historical narratives, ideology, and belief, this paper will show that contrary to the popular Abbasid narrative demonstrating the use of messianic expectation to gain power, in reality, the revolution was contingent on Abu Muslim's role as a messianic figurehead.

The decline of the Umayyad Caliphate and the subsequent rise of the Abbasid Empire represents a seminal chapter in Islamic history, marked by political upheaval, social discontent, and religious fervor. Under Umayyad rule, which commenced in 661 CE, the Islamic empire experienced significant territorial expansion and consolidation of power. However, the Umayyad era was also characterized by growing dissatisfaction among non-Arab Muslims, socio-economic disparities, and religious opposition. Non-Arab Muslims, particularly Persians and converts from other regions, felt marginalized by the Arab elite, while economic grievances and resentment over taxation policies fueled social unrest.^[Borrut, Antoine, and Paul M. Cobb. *Umayyad Legacies: Medieval Memories from Syria to Spain*. Brill, 2010, http://booksandjournals.brillonline.com/content/10.1163/ej.9789004184749.i-560.7.]

Concurrently, as the masses became dissatisfied with the conditions they lived in under the Umayyad rule, oppositional religious groups were gaining popularity through their dispersal of messianic ideas. Historian Jacob Lassner stated clearly, "As Umayyad rule began to unravel, there was a seeming rise in messianic expectation."^[Lassner, Jacob, and Michael Bonner. *Islam in the Middle Ages: The Origins and Shaping of Classical Islamic Civilization*. Praeger, 2010. Page 110.] This timely increase may be somewhat attributed to the inherent epochal nature of messianism in Islam, where the Mahdi will bring about a new era of prosperity. People can feel the Ummayad rule winding down, and with the impending end of a defining era for the arab world, there is of course the implied question of what will follow. Therefore, it is no huge leap for the hopeful, religious, or desperate to think that the end of the corrupt Umayyads could potentially usher in a new Messianic age.

This is the point in the story at which the two narratives begin to deviate. First, we will explore the side promoted by the Abbasid Caliphate, which is uncoincidentally the mainstream narrative adopted by historians. This narrative attributes the swift and decisive dismantling of the Umayad dynasty to a clandestine revolution orchestrated by the Abbasid family. The Abbasids were said to have connections to an underground network of revolutionaries, whom they were instructing to spread radical messianic ideology. This tactically planted the seeds of revolution among the common people of the Umayad Dynasty by pairing their political dissent with something to hope for. Lassner speaks more on this topic saying, "The marriage of a radical messianic message to revolutionary expectations is not unusual nor was it without its advantages to the house of 'Abbas. There was, after all, nothing to prevent abbasid propagandists from assuming a multitude of poses during the period of clandestine operations; they could thus appear as embracing all things to all peoples."^[Lassner, Jacob, and Michael Bonner. *Islam in the Middle Ages: The Origins and Shaping of Classical Islamic Civilization*. Praeger, 2010. Page 111.] This interpretation from Lassner emphasizes both the intentionality behind the Abbasid's Mahdist propaganda as well as how the underground nature of the operation allowed them to appeal to multiple groups by spreading inconsistent messages. Through strategic manipulation of religious symbolism and apocalyptic belief, the Abbasid authority undermined public faith in the Umayyad regime.

The Abbasids had successfully set the stage for a new Caliphate, now all that had to be done was to insert themselves into that role. This was done by strategically invoking their familial connection to the Prophet Muhammad through his uncle Abbas, thereby legitimizing their claim to the caliphate based on lineage. This genealogical tie provided the Abbasids with a powerful narrative of legitimacy, especially now appealing to an array of proto-Shi'ite groups who strongly believed in the importance of the Caliph being from the lineage of the prophet Muhammad.

With the tactical use of clandestine revolution, the Umayyad Caliphate was toppled swiftly and decisively. The people had been primed, waiting for a Mahdi figure to come and end the era of the Umayyad. So, when the Abbasids rode in with their black banners, opposing the white of the Umayyads, many were already on their side. The Abbasids effectively harnessed the energy of this apocalypticism paired with their lineage and within three years they controlled the entire Arabian Peninsula.

This narrative of the Abbasid revolution makes perfect sense when understanding the notion that history is written by the victors. It frames the Abbasids as tactful, powerful, and most of all in control of the workings that ultimately enabled their five-hundred-year Caliphate. As it applies to eschatological understanding, this telling teaches us that the invocation of the Mahdi symbol paired with the necessary lineage is enough to gain immense political power. This understanding places a lot of power on pure anticipation of the Mahdi, without necessitating the use of a prominent figurehead. But, this is not the complete narrative. What aspects of the transfer of power would the Abbasids prefer to be left out of the history books, and how does uncovering this information affect our understanding of the eschatological implications?

The first of those questions is easy to answer, clearly, from his lack of mention in their literature, the Abbasids would prefer we forget about Abu Muslim. However, while he may not be a focal point in the narrative of the Abbasid Revolution, his story was not lost. Abu Muslim's early life and identity are shrouded in mystery and subject to conflicting accounts. He hailed from an obscure and non-Arab background, with various reports suggesting noble Persian descent or ties to the disowned Abbasid lineage.^[Ibn al-Athīr, *al-Kāmil fī l-ta'rīkh*, vol. 4, Beirut 1986. Page 64-67.] However, his own description of himself states, "I am a man from the muslimūn; I do not affiliate myself with any tribe to the exclusion of another."^[Anon., *Akhbār al-dawla al-'Abbāsiyya wa-fīhi akhbār al-'Abbās wa-waladih*, ed. 'Abd al-'Azīz al-Dūrī and 'Abd al-Jabbār al-Muṭṭalibī, Beirut 1971. Page 82.] This deliberate obscurity and clear allegiance to Islam frames him as a man of the people, with clear potential as a unifying force. As a young activist, Abu Muslim traversed the Iranian landscape, forging connections with disenfranchised groups and radical Shia sects. These are the same sects as those aforementioned for their role in spreading messianic anticipation. His association with the Banū'Ijl tribe and eventual entry into the Hāshimiyya organization (one of the Shi'ite sects),^[Britannica, The Editors of Encyclopaedia. "Hāshimīyah". *Encyclopedia Britannica*, 11 Jul. 2007, https://www.britannica.com/topic/Hashimiyah. Accessed 8 May 2024.] provided him with a platform to mobilize support and channel dissent against Umayyad rule. Described as, "charismatic, resolute, and high-minded,"^[Agha, Seleh said. "Abū Muslim Al-Khurāsānī." Referenceworks, *Encyclopaedia of Islam Three*, 2007, referenceworks.brill.com/display/entries/EI3O/COM-24741.xml?rskey=zJycCU&result=1.] with access to the Hāshimiyya, and a strategic mindset, Abu Muslim positioned himself as a key figure in the revolutionary movement.

Serving as a leader on behalf of the Hāshimiyya, who were religiously opposed to the Ummayad Caliphate, Abu Muslim traveled to Mecca in search of a riḍā (acceptable candidate) to serve as the next Imam. The person had to be from the lineage of the prophet Muhammad's great-grandfather Hāshim, and once chosen, the new Imam would be backed by the Hāshimiyya. Assessing his options, the Alīds had the strongest historical and genealogical claim to legitimacy, whereas the Abbāsids had never previously exercised such a claim. However, unlike other members of the Hāshimiyya, Abu Muslim was not solely concerned with finding a riḍā. The Encyclopaedia of Islam states, "He was probably looking for the weakest claimant, the one least suspect of subversive or revolutionary intentions, connections, and/or capabilities and thus the candidate best suited to his designs."^[Agha, Seleh said. "Abū Muslim Al-Khurāsānī." Referenceworks, *Encyclopaedia of Islam Three*, 2007, referenceworks.brill.com/display/entries/EI3O/COM-24741.xml?rskey=zJycCU&result=1] Seemingly due to these reasons, he selected the Abbasids, cutting a deal with the son of their chief, Ibrāhīm al-Imām, whereby the Abbasids would bring religious leadership and legitimacy, and Abu Muslim would provide mobilized forces. If successful they would divide the spoils and split the land down the line of the Tigris River.^[Daniel C. Dennett, *Marwān ibn Muḥammad. The passing of the Umayyad caliphate*, Ph.D. diss., Harvard University 1939. Page 124-125.]

This strategic alliance with the Abbasid family was the beginning of Abu Muslims' ultimate ascension to power. Within a few weeks of returning from Mecca, he had effectively gained control of the Hāshimiyya, now holding immense influence over the masses who had been recently converted by the various Shi'ite sects spreading their messianic prophecies. With this final piece in place, he was ready for an open revolution.

Abu Muslim's overthrow of the Umayyad Caliphate began with orchestrated rebellions in outlying districts, overpowering Arab garrisons, and destabilizing power centers like Merv. With minimal confrontation, Merv fell to Abu Muslim, signaling the collapse of Umayyad dominance in the eastern region.^[al-Dīnawarī, *al-Akhbār al-ṭiwāl*, ed. Vladimir Guirgass, Leiden 1888] He then dispatched armies to abolish Umayyad rule in the West. There, his forces triumphantly entered Kufa, where he orchestrated a coup installing Abu al-Abbas al-Saffah, the youngest of the Abbasid brothers, as the first Abbasid caliph. As stated in the Encyclopaedia of Islam, "The amazing rapidity of the collapse of the Arab Umayyad military might in Khurāsān and Transoxania can be understood only by understanding Abū Muslim's extraordinary strategy."^[Agha, Seleh said. "Abū Muslim Al-Khurāsānī." Referenceworks, *Encyclopaedia of Islam Three*, 2007, referenceworks.brill.com/display/entries/EI3O/COM-24741.xml?rskey=zJycCU&result=1. Section 2.3.] With al-Saffāḥ now serving as Caliph, and Abu Muslim maintaining governmental and military control, this marked the end of the Umayyad Caliphate and the rise of the Abbasid Dynasty.

Understanding the hidden story of Abu Muslim, it feels clear in hindsight that the Abbasids would not have been able to gain control of the caliphate had they not initially been chosen by Abu Muslim, and later benefitted from his military prowess. Now, recognizing the integral role Abu Muslim played in the Abbasid Revolution, I feel compelled to ask the question, was he serving as a messianic figure?

The answer is not completely clear. Firstly, from all known accounts he never personally claimed to be the Mahdi or displayed much interest in religious leadership. However, ultimately he was the one to activate a massive buildup of messianic anticipation into a full blown revolution. He brought about the end of the Umayyad Caliphate as the Mahdi was expected to do, not to mention accounts of his charisma. So, even if he never officially claimed the title, from the lens of functionality, Abu Muslim played the role of a messianic figure in the Abbasid Revolution.

Understanding Abu Muslim as a messianic figurehead who was integral in the success of the Abbasid Revolution completely reshapes our understanding of the eschatological implications at play. Previously, based on the Abbasid narrative, we are led to believe that due to the prophecy surrounding and lineage of the Abbasid, the messianic expectation, paired with some political unrest, was enough to start a revolution. However, Abu Muslim's story shows us that is just not the case. On the contrary, the complete story of the Abbasid's rise emphasizes the importance of having a figurehead in order to activate messianic belief among the public and create tangible change.

So, if Abu Muslim's role in the Abbasid Revolution was so crucial, why is he missing from the Abbasid narrative? After dismantling the Umayad Caliphate and installing Abū l-'Abbās al-Saffāḥ as the first Abbasid Caliph, Abu Muslim began to rule alongside the Abbasids. Similarly to his reasons for choosing the Abbasid family in the first place, Abu Muslim intentionally chose al-Saffāḥ as the youngest and weakest of the eligible Abbasid brothers to be the first Caliph.^[Agha, Saleh Said. "The Revolution which toppled the Umayyads: Neither Arab nor Ἁbbāsid." *The Revolution which toppled the Umayyads*. Brill, 2003.] Ruling alongside al-Saffāḥ allowed Abu Muslim to maintain the power he had gained in the Abbasid Revolution as the central leader. Throughout this period he was feared by the Abbasid family. However, although the initial claim to power felt contingent on the reputation of Abu Muslims, over the first few years of the dynasty Abbasid legitimacy had taken root, partially due to Abu Muslim's efforts to cultivate it. Ultimately, after a five-year stint, Abū l- Abbās al-Saffāḥ was succeeded by his older brother, Abū Ja'far al-Manṣūr. The new Caliph did not take as kindly to the control of Abu Muslim as his younger brother. Seeing him as more of a threat than an asset, after eight months as Caliph, Al-Manṣūr covertly murdered Abu Muslim, finally allowing the Abbasids to take complete control of the caliphate.

The story of Abu Muslim, while often overshadowed by the mainstream narrative of the Abbasid Revolution, emerges as a crucial aspect in understanding the eschatological dimensions inherent in the rise of the Abbasid Empire. Through his strategic alliances and mobilization of messianic aspirations, Abu Muslim played a pivotal role in the swift overthrow of the Umayyad Caliphate and the subsequent establishment of Abbasid rule. His deliberate obscurity and clear allegiance to Islam positioned him as a unifying force among the disenfranchised masses, ultimately leading to his instrumental role in orchestrating open revolution. While Abu Muslim may not have personally claimed the title of the Mahdi, his functional role as a messianic figurehead cannot be ignored. Understanding his integral role reshapes our understanding of the eschatological implications at play, emphasizing the importance of a figurehead in activating messianic belief and effecting tangible change. Despite his significant contributions, Abu Muslim's absence from the Abbasid narrative serves as a classic example of revisionist history, where ending on top allows the Abbasids to paint their own picture, with themselves at the center. Abu Muslim reminds us that behind every dominant narrative lies a wealth of untold stories, waiting to reshape our understanding of the past.

## Bibliography

